from snakemake.utils import min_version

min_version("7.12.1")


configfile: "config/config.yaml"


EMAIL = config["email"]
RUNID = config["run_id"]
OUTPUT = config["output"]
REF_DOWNLOADS = "resources/downloaded_ref_files"
HOST = config["host_organism"]
HOST_FILE = config["host_genome"]
HOST_DOWNLOAD = f"{HOST.replace(' ', '_')}_ref_genome.fna.gz"
VIRUSES = config["viral_genomes"]
STRAIN_DB = config["strain_db"]
BARCODES = config["barcodes"]
READS = config["reads"]
SIMILARITY = config["similarity_threshold"]
FASTMAP = config.get("blat_fast_map", True)
CROPLEN = config["crop_len"]
CUTOFF = config["sftclp_cutoff"]
RVHAPLO_MAX_ALIGNMENTS = config["rvhaplo_max_alignments"]
RVHAPLO_MAX_ALIGNMENT_BASES = config["rvhaplo_max_alignment_bases"]
OUTDIR = OUTPUT + RUNID
LOGDIR = f"{OUTDIR}/snakemake_logs"
BENCHDIR = f"{OUTDIR}/snakemake_benchmarks"
SAMPLES = [f for f in os.listdir(READS) if not f.startswith(".")]


def get_samples_with_viral_targets(wildcards):
    """
    Called after checkpoint get_viral_genomes completes.
    Returns RVHaplo output paths only for samples that found viral targets.
    """
    # Force checkpoint evaluation for all samples
    for sample in SAMPLES:
        checkpoints.get_viral_genomes.get(sample=sample)

    # Check which samples have the success marker
    samples_with_targets = []
    for sample in SAMPLES:
        marker = f"{OUTDIR}/{sample}_VIRAL_TARGETS_FOUND"
        if os.path.exists(marker):
            samples_with_targets.append(sample)

    return expand(
        f"{OUTDIR}/{{sample}}_rvhaplo_results_table.tsv", sample=samples_with_targets
    )


ALL_INPUT = [
    f"{OUTDIR}/on_target_stats.tsv",
    expand(f"{OUTDIR}/{{sample}}_reads_per_strain_samtools.idxstats", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_pre_dedup_rl.tsv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_post_dedup_rl.tsv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_reads_per_strain_filtered.tsv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_start_read_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_hard_trim_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_chimeric_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_viral_targets.log", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_viral_target_genomes.fasta", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_add_sample_info.done", sample=SAMPLES),
    get_samples_with_viral_targets,
]


rule all:
    input:
        ALL_INPUT,


if STRAIN_DB == "" and not os.path.exists(f"{REF_DOWNLOADS}/strain_db.tsv"):

    include: "rules/strain_db.smk"


if STRAIN_DB == "":

    STRAIN_DB = f"{REF_DOWNLOADS}/strain_db.tsv"


if HOST_FILE == "" and not os.path.exists(f"{REF_DOWNLOADS}/{HOST_DOWNLOAD}"):

    include: "rules/get_host_ref.smk"


if HOST_FILE == "":

    HOST_FILE = f"{REF_DOWNLOADS}/{HOST_DOWNLOAD}"


# old `viral_bed.smk`
rule viral_bed:
    input:
        viruses=VIRUSES,
    output:
        bed=temp(f"{OUTDIR}/all_viral_targets.bed"),
    log:
        f"{LOGDIR}/viral_bed_snakemake.log",
    benchmark:
        f"{BENCHDIR}/viral_bed.benchmark"
    conda:
        "envs/alignment.yaml"
    shell:
        "samtools faidx {input.viruses:q}; "
        "cat {input.viruses:q}.fai | "
        "awk '{{print $1\"\t0\t\"$2}}' >  {output.bed:q}; "
        "rm {input.viruses:q}.fai"


# old `concat_parts.smk`
rule concat_parts:
    input:
        reads=f"{READS}/{{sample}}",
    output:
        fastq=temp(f"{OUTDIR}/{{sample}}_concat.fastq.gz"),
    log:
        f"{LOGDIR}/{{sample}}_concat_parts_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_concat_parts.benchmark"
    conda:
        "envs/default.yaml"
    shell:
        "cat {input.reads:q}/* > {output.fastq:q}"


# old `start_read_counts.smk`
rule start_read_count:
    input:
        fastq=rules.concat_parts.output.fastq,
    output:
        counts=f"{OUTDIR}/{{sample}}_start_read_count.txt",
    log:
        f"{LOGDIR}/{{sample}}_read_count_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_read_counts.benchmark"
    conda:
        "envs/default.yaml"
    shell:
        "bash workflow/scripts/start_counts.sh {input.fastq:q} {output.counts:q}"


# old `trim_reads.smk`
rule trim_reads:
    input:
        fastq=rules.concat_parts.output.fastq,
    output:
        logfile=f"{OUTDIR}/{{sample}}_trimmed.log",
        trimmed_reads=f"{OUTDIR}/{{sample}}_trimmed.fastq.gz",
    log:
        f"{LOGDIR}/{{sample}}_trim_reads_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_trim_reads.benchmark"
    conda:
        "envs/trimming.yaml"
    params:
        crop=CROPLEN,
        barcodes=BARCODES,
    shell:
        "python workflow/scripts/trim.py "
        "--infile {input.fastq:q} "
        "--logfile {output.logfile:q} "
        "--outfile {output.trimmed_reads:q} "
        "--barcodes {params.barcodes:q} "
        "--crop {params.crop}"


# old `trim_counts.smk`
rule hard_trim_count:
    input:
        log=rules.trim_reads.output.logfile,
    output:
        counts=f"{OUTDIR}/{{sample}}_hard_trim_count.txt",
    log:
        f"{LOGDIR}/{{sample}}_hard_trim_count_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_hard_trim_count.benchmark"
    conda:
        "envs/default.yaml"
    shell:
        "cat {input.log:q} | "
        "awk '{{ if ($0 ~ /short/) print }}' | "
        "wc -l > {output.counts:q}"


rule chimeric_count:
    input:
        fastq=rules.trim_reads.output.trimmed_reads,
    output:
        counts=f"{OUTDIR}/{{sample}}_chimeric_count.txt",
    log:
        f"{LOGDIR}/{{sample}}_chimer_count_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_chimer_count.benchmark"
    conda:
        "envs/default.yaml"
    shell:
        "gzip -dc {input.fastq:q} | "
        "awk '{{ if ($0 ~ /_A/ || $0 ~ /_B/) print $0 }}' | "
        "wc -l > {output.counts:q}"


# old `deduplicate.smk`
rule bin_reads_by_length:
    input:
        fastq=rules.trim_reads.output.trimmed_reads,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_bin_reads.done"),
    log:
        f"{LOGDIR}/{{sample}}_bin_reads_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_bin_reads.benchmark"
    conda:
        "envs/deduplication.yaml"
    params:
        outdir=f"{OUTDIR}/{{sample}}_read_bins",
    shell:
        "mkdir -p {params.outdir:q}; "
        "python workflow/scripts/bin_reads.py "
        "--infile {input.fastq:q} "
        "--outdir {params.outdir:q}"


rule cluster_reads:
    input:
        flag=rules.bin_reads_by_length.output.flag,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_cluster_reads.done"),
    log:
        f"{LOGDIR}/{{sample}}_cluster_reads_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_cluster_reads.benchmark"
    conda:
        "envs/deduplication.yaml"
    params:
        similarity_threshold=SIMILARITY,
        indir=f"{OUTDIR}/{{sample}}_read_bins",
        outdir=f"{OUTDIR}/{{sample}}_read_clusters",
    shell:
        "mkdir -p {params.outdir:q}; "
        "python workflow/scripts/cluster_reads.py "
        "--threshold {params.similarity_threshold} "
        "--indir {params.indir:q} "
        "--outdir {params.outdir:q}; "
        "rm -rf {params.indir:q}; "
        "rm {input:q}"


rule blat_clustered_reads:
    input:
        flag=rules.cluster_reads.output.flag,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_blat.done"),
    log:
        f"{LOGDIR}/{{sample}}_blat_reads_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_blat.benchmark"
    conda:
        "envs/deduplication.yaml"
    threads: 32
    params:
        rc=f"{OUTDIR}/{{sample}}_read_clusters/",
        o=f"{OUTDIR}/{{sample}}_psl_files/",
        fast_map_flag=lambda wildcards: "--fast_map" if FASTMAP else "",
    shell:
        "mkdir -p {params.o:q}; "
        "python workflow/scripts/run_blat.py "
        "--outdir {params.o:q} "
        "--threads {threads} "
        "--read_clusters {params.rc:q} "
        "{params.fast_map_flag}; "
        "rm -rf {params.rc:q}; "
        "rm {input:q}"


rule find_duplicates:
    input:
        flag=rules.blat_clustered_reads.output.flag,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_find_duplcates.done"),
    log:
        f"{LOGDIR}/{{sample}}_find_dups_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_find_dups.benchmark"
    conda:
        "envs/deduplication.yaml"
    threads: 8
    params:
        similarity_threshold=SIMILARITY,
        pls_dir=f"{OUTDIR}/{{sample}}_psl_files/",
        outdir=f"{OUTDIR}/{{sample}}_duplicate_txts/",
    shell:
        "python workflow/scripts/find_duplicates.py "
        "-p {params.pls_dir:q} "
        "-o {params.outdir:q} "
        "-s {params.similarity_threshold} "
        "-t {threads}; "
        "rm -rf {params.pls_dir:q}; "
        "rm {input:q}"


rule merge_duplicates_lists:
    input:
        flag=rules.find_duplicates.output.flag,
    output:
        dups=f"{OUTDIR}/{{sample}}_duplicates.txt",
    log:
        f"{LOGDIR}/{{sample}}_merge_dup_lists_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_merge_dups_lists.benchmark"
    conda:
        "envs/default.yaml"
    params:
        indir=f"{OUTDIR}/{{sample}}_duplicate_txts",
    shell:
        "cat {params.indir:q}/* > {output.dups:q}; rm -rf {params.indir:q}"


rule deduplicate:
    input:
        reads=rules.trim_reads.output.trimmed_reads,
        duplicates_list=rules.merge_duplicates_lists.output.dups,
    output:
        reads=f"{OUTDIR}/{{sample}}_dedup.fastq.gz",
        dupes=f"{OUTDIR}/{{sample}}_dup_reads.fastq.gz",
    log:
        f"{LOGDIR}/{{sample}}_dedup_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_dedup.benchmark"
    conda:
        "envs/deduplication.yaml"
    shell:
        "python workflow/scripts/deduplicate.py "
        "--reads {input.reads:q} "
        "--duplicates {input.duplicates_list:q} "
        "--out_reads {output.reads:q} "
        "--out_dupes {output.dupes:q}"


# old `dup_read_lengths.smk
rule pre_dedup_read_lengths:
    input:
        fastq=rules.trim_reads.output.trimmed_reads,
    output:
        rl=f"{OUTDIR}/{{sample}}_pre_dedup_rl.tsv",
    log:
        f"{LOGDIR}/{{sample}}_pre_dedup_rl_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_pre_dedup_rl.benchmark"
    conda:
        "envs/deduplication.yaml"
    shell:
        "python workflow/scripts/read_lengths.py "
        "--infile {input.fastq:q} "
        "--outfile {output.rl:q}"


rule post_dedup_read_lengths:
    input:
        fastq=rules.deduplicate.output.reads,
    output:
        rl=f"{OUTDIR}/{{sample}}_post_dedup_rl.tsv",
    log:
        f"{LOGDIR}/{{sample}}_post_dedup_rl_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_post_dedup_rl.benchmark"
    conda:
        "envs/deduplication.yaml"
    shell:
        "python workflow/scripts/read_lengths.py "
        "--infile {input.fastq:q} "
        "--outfile {output.rl:q}"


# old `host_removal.smk`
rule align_reads_to_host:
    input:
        host=HOST_FILE,
        samples=rules.deduplicate.output.reads,
    output:
        sam=temp(f"{OUTDIR}/{{sample}}_host.sam"),
    log:
        f"{LOGDIR}/{{sample}}_ato_host_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_ato_host.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    shell:
        "minimap2 --secondary=no "
        "-t {threads} "
        "-o {output.sam:q} "
        "-a {input.host:q} {input.samples:q}"


rule host_sam_to_bam:
    input:
        sam=rules.align_reads_to_host.output.sam,
    output:
        bam=temp(f"{OUTDIR}/{{sample}}_host_sorted.bam"),
    log:
        f"{LOGDIR}/{{sample}}_host_sam2bam_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_host_sam2bam.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    shell:
        "samtools view -Sb {input.sam:q} | samtools sort -@ {threads} -o {output.bam:q}"


rule remove_host_dna:
    input:
        bam=rules.host_sam_to_bam.output.bam,
    output:
        idx=temp(f"{OUTDIR}/{{sample}}_remove_host_samtools.idxstats"),
        bam=temp(f"{OUTDIR}/{{sample}}_host_removed_sorted.bam"),
    log:
        f"{LOGDIR}/{{sample}}_host_removal_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_host_removal.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 10
    shell:
        "samtools index {input.bam:q} && "
        "samtools view -h -F 2048 -b {input.bam:q} | "
        "samtools idxstats - > {output.idx:q}; "
        "samtools view -h -f 4 -b {input.bam:q} -o {output.bam:q}; "
        "rm {input.bam:q}.bai"


rule non_host_reads:
    input:
        bam=rules.remove_host_dna.output.bam,
    output:
        fastq=f"{OUTDIR}/{{sample}}_non_host.fastq.gz",
    log:
        f"{LOGDIR}/{{sample}}_non_host_reads_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_non_host_reads.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 4
    shell:
        "samtools fastq {input.bam:q} | bgzip -@ {threads} -c > {output.fastq:q}"


# old `host_removal_stats.smk`
rule host_removal_stats:
    input:
        expand(f"{OUTDIR}/{{sample}}_remove_host_samtools.idxstats", sample=SAMPLES),
    output:
        tsv=temp(f"{OUTDIR}/host_removal_stats.tsv"),
    log:
        f"{LOGDIR}/host_removal_stats_snakemake.log",
    benchmark:
        f"{BENCHDIR}/host_removal_stats.benchmark"
    conda:
        "envs/alignment.yaml"
    shell:
        "python workflow/scripts/samtools_idxstats.py -i {input:q} -o {output:q}"


# old `stats_alignment.smk`
rule align_to_viruses_for_stats_no_secondary:
    input:
        viruses=VIRUSES,
        samples=rules.non_host_reads.output.fastq,
    output:
        sam=temp(f"{OUTDIR}/{{sample}}_stats_viruses.sam"),
    log:
        f"{LOGDIR}/{{sample}}_ato_viruses_4stats_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_ato_viruses_4stats.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    shell:
        "minimap2 "
        "--secondary=no "
        "--q-occ-frac 0 "
        "-f 0 "
        "-t {threads} "
        "-o {output.sam:q} "
        "-a {input.viruses:q} {input.samples:q}"


# old `on_target_stats.smk`
rule viruses_alignment_stats:
    input:
        sam=rules.align_to_viruses_for_stats_no_secondary.output.sam,
    output:
        idx=temp(f"{OUTDIR}/{{sample}}_all_viruses_samtools.idxstats"),
    log:
        f"{LOGDIR}/{{sample}}_stat_align_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_stat_align.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    params:
        cutoff=CUTOFF,
        bam=f"{OUTDIR}/{{sample}}_stats_viruses_sorted.bam",
        sftbam=f"{OUTDIR}/{{sample}}_stats_viruses_sorted_sftclp.bam",
    shell:
        "samtools view -h -F 2048 -Sb {input.sam:q} | "
        "samtools sort -@ {threads} -o {params.bam:q}; "
        "samtools index -@ {threads} {params.bam:q}; "
        "python workflow/scripts/sftclipper.py "
        "--cutoff {params.cutoff} "
        "--bam {params.bam:q} "
        "--outfile {params.sftbam:q}; "
        "samtools index -@ {threads} {params.sftbam:q}; "
        "samtools idxstats {params.sftbam:q} > {output.idx:q}; "
        "rm {params.bam:q} {params.bam:q}.bai; "
        "rm {params.sftbam:q} {params.sftbam:q}.bai"


rule merge_viral_alignment_stats:
    input:
        expand(f"{OUTDIR}/{{sample}}_all_viruses_samtools.idxstats", sample=SAMPLES),
    output:
        tsv=temp(f"{OUTDIR}/all_viruses_stats.tsv"),
    log:
        f"{LOGDIR}/merge_viral_stats_snakemake.log",
    benchmark:
        f"{BENCHDIR}/merge_viral_stats.benchmark"
    conda:
        "envs/alignment.yaml"
    shell:
        "python workflow/scripts/samtools_idxstats.py -i {input:q} -o {output:q}"


rule on_target_stats:
    input:
        viral_stats=rules.merge_viral_alignment_stats.output.tsv,
        host_stats=rules.host_removal_stats.output.tsv,
    output:
        tsv=f"{OUTDIR}/on_target_stats.tsv",
    log:
        f"{LOGDIR}/on_target_stats_snakemake.log",
    benchmark:
        f"{BENCHDIR}/on_target_stats.benchmark"
    conda:
        "envs/alignment.yaml"
    shell:
        "python workflow/scripts/merge_stats.py "
        "--host_stats {input.host_stats:q} "
        "--viral_stats {input.viral_stats:q} "
        "--outfile {output.tsv:q}"


# old `viral_alignment.smk`
rule align_to_viruses_with_secondary:
    input:
        viruses=VIRUSES,
        samples=rules.non_host_reads.output.fastq,
    output:
        sam=temp(f"{OUTDIR}/{{sample}}_viruses.sam"),
    log:
        f"{LOGDIR}/{{sample}}_ato_viruses_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_ato_viruses.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    shell:
        "minimap2 "
        "--q-occ-frac 0 "
        "-f 0 "
        "-t {threads} "
        "-o {output.sam:q} "
        "-a {input.viruses:q} {input.samples:q}"


rule viruses_sam_to_bam:
    input:
        sam=rules.align_to_viruses_with_secondary.output.sam,
    output:
        bam=f"{OUTDIR}/{{sample}}_viruses_sorted_sftclp.bam",
        idx=temp(f"{OUTDIR}/{{sample}}_reads_per_strain_samtools.idxstats"),
    log:
        f"{LOGDIR}/{{sample}}_viral_sam2bam_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_viral_sam2bam.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    params:
        cutoff=CUTOFF,
        tmp_bam=f"{OUTDIR}/{{sample}}_viruses_sorted.bam",
    shell:
        "samtools view -Sb {input.sam:q} | "
        "samtools sort -@ {threads} -o {params.tmp_bam:q}; "
        "samtools index -@ {threads} {params.tmp_bam:q}; "
        "python workflow/scripts/sftclipper.py "
        "--cutoff {params.cutoff} "
        "--bam {params.tmp_bam:q} "
        "--outfile {output.bam:q}; "
        "samtools index -@ {threads} {output.bam:q}; "
        "samtools view -h -F 2048 -b {output.bam:q} | "
        "samtools idxstats - > {output.idx:q}; "
        "rm {params.tmp_bam:q} {params.tmp_bam:q}.bai"


# old `reads_per_strain.smk`
rule reads_per_strain:
    input:
        stats=rules.viruses_sam_to_bam.output.idx,
        strain_db=STRAIN_DB,
    output:
        tsv=f"{OUTDIR}/{{sample}}_reads_per_strain.tsv",
    log:
        f"{LOGDIR}/{{sample}}_reads_per_strain_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_reads_per_strain.benchmark"
    conda:
        "envs/alignment.yaml"
    shell:
        "python workflow/scripts/summarize_idxstats.py "
        "--infile {input.stats:q} "
        "--strains {input.strain_db:q} "
        "--outfile {output.tsv:q}"


rule filter_reads_per_strain:
    input:
        tsv=rules.reads_per_strain.output.tsv,
    output:
        tsv=f"{OUTDIR}/{{sample}}_reads_per_strain_filtered.tsv",
    log:
        f"{LOGDIR}/{{sample}}_filtered_reads_per_strain_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_filtered_reads_per_strain.benchmark"
    conda:
        "envs/default.yaml"
    shell:
        "cat {input.tsv:q} | awk -F'\t' '{{ if($3 > 0) print}}' > {output.tsv:q}"


# old `find_viral_targets.smk`
rule mpileup:
    input:
        bam=rules.viruses_sam_to_bam.output.bam,
    output:
        pileup=f"{OUTDIR}/{{sample}}.mpileup",
    log:
        f"{LOGDIR}/{{sample}}_mpileup_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_mpileup.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 10
    shell:
        "samtools mpileup --output-QNAME {input.bam:q} | "
        "awk '{{print $1\"\t\"$4}}' - > {output.pileup:q}"


rule find_viral_targets:
    input:
        pileup=rules.mpileup.output.pileup,
        all_viruses_bed=f"{OUTDIR}/all_viral_targets.bed",
        strain_db=STRAIN_DB,
    output:
        bed=temp(f"{OUTDIR}/{{sample}}_viral_targets.bed"),
        logfile=f"{OUTDIR}/{{sample}}_viral_targets.log",
        selected_log=f"{OUTDIR}/{{sample}}_selected_viral_targets.log",
    log:
        f"{LOGDIR}/{{sample}}_viral_targets_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_viral_targets.benchmark"
    conda:
        "envs/alignment.yaml"
    params:
        email=EMAIL,
    shell:
        "python workflow/scripts/find_viral_targets.py "
        "--mpileup {input.pileup:q} "
        "--bed {input.all_viruses_bed:q} "
        "--strains {input.strain_db:q} "
        "--logfile {output.logfile:q} "
        "--outfile {output.bed:q}; "
        "python workflow/scripts/add_viral_segments.py "
        "--infile {output.logfile:q} "
        "--email {params.email:q}; "
        "awk -F'\t' '{{ if($3 > 80.0) print}}' {output.logfile:q} "
        "> {output.selected_log:q}"


checkpoint get_viral_genomes:
    input:
        fasta=VIRUSES,
        bed=rules.find_viral_targets.output.bed,
    output:
        f"{OUTDIR}/{{sample}}_viral_target_genomes.fasta",
    log:
        f"{LOGDIR}/{{sample}}_get_viral_genomes_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_get_viral_genomes.benchmark"
    conda:
        "envs/alignment.yaml"
    params:
        succeed=f"{OUTDIR}/{{sample}}_VIRAL_TARGETS_FOUND",
        fail=f"{OUTDIR}/{{sample}}_NO_VIRAL_TARGETS",
    shell:
        "bedtools getfasta -fi {input.fasta:q} -bed {input.bed:q} -fo {output:q}; "
        "if grep -q . {output:q}; then touch {params.succeed:q}; else touch {params.fail:q}; fi"


# old `add_sample_info.smk`
rule add_sample_info:
    input:
        rules.pre_dedup_read_lengths.output.rl,
        rules.post_dedup_read_lengths.output.rl,
        rules.reads_per_strain.output.tsv,
        rules.filter_reads_per_strain.output.tsv,
        rules.find_viral_targets.output.logfile,
        rules.find_viral_targets.output.selected_log,
    output:
        touch(f"{OUTDIR}/{{sample}}_add_sample_info.done"),
    log:
        f"{LOGDIR}/{{sample}}_sample_info_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_add_sample_info.benchmark"
    conda:
        "envs/default.yaml"
    params:
        run_id=RUNID,
        sample_id="{sample}",
    shell:
        "python workflow/scripts/add_run_info.py "
        "--sample_id {params.sample_id:q} "
        "--run_id {params.run_id:q} "
        "--infiles {input:q}"


## HAPLOTYPE GENERATION ########################################################
rule split_viral_genomes:
    input:
        fasta=f"{OUTDIR}/{{sample}}_viral_target_genomes.fasta",
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_viral_refs.done"),
    log:
        f"{LOGDIR}/{{sample}}_split_viral_genomes_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_split_viral_genomes.benchmark"
    conda:
        "envs/alignment.yaml"
    params:
        outdir=f"{OUTDIR}/{{sample}}_viral_refs/",
    shell:
        "bash workflow/scripts/split_target_viruses.sh {input.fasta:q} {params.outdir:q}"


rule align_to_target_virus:
    input:
        flag=rules.split_viral_genomes.output.flag,
        reads=rules.non_host_reads.output.fastq,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_align_to_targets.done"),
    log:
        f"{LOGDIR}/{{sample}}_align_to_targets_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_align_to_targets.benchmark"
    conda:
        "envs/alignment.yaml"
    threads: 32
    params:
        indir=f"{OUTDIR}/{{sample}}_viral_refs/",
        outdir=f"{OUTDIR}/{{sample}}_target_aligned/",
        sample="{sample}",
    shell:
        "bash workflow/scripts/align_to_targets.sh "
        "{params.outdir:q} "
        "{params.indir:q} "
        "{params.sample:q} "
        "{input.reads:q} "
        "{threads}"


rule run_rvhaplo:
    input:
        flag=rules.align_to_target_virus.output.flag,
    output:
        flag=touch(f"{OUTDIR}/{{sample}}_rvhaplo.done"),
        preflight=f"{OUTDIR}/{{sample}}_rvhaplo_out/rvhaplo_preflight.tsv",
    log:
        f"{LOGDIR}/{{sample}}_run_rvhaplo_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_run_rvhaplo.benchmark"
    conda:
        "envs/rvhaplo.yaml"
    threads: 32
    params:
        sample="{sample}",
        vir_indir=f"{OUTDIR}/{{sample}}_viral_refs/",
        sam_indir=f"{OUTDIR}/{{sample}}_target_aligned/",
        outdir=f"{OUTDIR}/{{sample}}_rvhaplo_out/",
        max_alignments=RVHAPLO_MAX_ALIGNMENTS,
        max_alignment_bases=RVHAPLO_MAX_ALIGNMENT_BASES,
    shell:
        "bash workflow/scripts/run_rvhaplo.sh "
        "{params.outdir:q} "
        "{params.vir_indir:q} "
        "{params.sam_indir:q} "
        "{params.sample:q} "
        "{threads} "
        "{params.max_alignments:q} "
        "{params.max_alignment_bases:q}"


rule parse_rvhaplo_out:
    input:
        flag=rules.run_rvhaplo.output.flag,
        strain_db=STRAIN_DB,
    output:
        tsv=f"{OUTDIR}/{{sample}}_rvhaplo_results_table.tsv",
    log:
        f"{LOGDIR}/{{sample}}_parse_rvhaplo_snakemake.log",
    benchmark:
        f"{BENCHDIR}/{{sample}}_parse_rvhaplo.benchmark"
    conda:
        "envs/rvhaplo.yaml"
    params:
        indir=f"{OUTDIR}/{{sample}}_rvhaplo_out/",
    shell:
        "python workflow/scripts/parse_rvhaplo.py "
        "--indir {params.indir:q} "
        "--strains {input.strain_db:q} "
        "--outfile {output:q}"


onsuccess:
    shell("rm -rf -- {LOGDIR:q}")
