email: ""
run_id: "test"
output: "test_results/"

host_genome: "data/host/"
viral_genomes: "data/viruses/"
strain_db: ""
reads: "data/raw/"
silimarity_threshold: 0.9
crop_len: 37
barcodes: "data/barcodes/"
sftclp_cutoff: 0.5

rvhaplo_repo: "https://github.com/dhcai21/RVHaplo.git"
strainline_repo: "https://github.com/HaploKit/Strainline.git"